baseURL = "https://blog.curtpoff.com"
languageCode = "en-us"
title = "Curt Poff"
theme = "LeaveIt"
disqusShortname = "cpoff"
enableRobotsTXT = true
googleAnalytics = "UA-315392-10"
paginate = 15
rss = true
enableEmoji = false
preserveTaxonomyNames = true

[taxonomies]
    tag = "tags"
    category = "categories"
    series = "series"

[permalinks]
    posts = "/:title/"

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "Blog"
    url = "/posts/"
    weight = 10

  [[menu.main]]
    name = "Categories"
    url = "/categories/"
    weight = 20

  [[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 30

  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 40

[params]
#    since = 2011
    author = "Curt Poff"                           # Author's name
    avatar = "/androidify300.png"           # Author's avatar
    subtitle = "Web guy, beer drinker, sports fan"         # Subtitle
    cdn_url = ""  # Base CDN URL
    home_mode = "" # post or other
    google_verification = ""
    description = "Curt Poff is a veteran techie now living in Tucson. Past homes include Portland and the Bay Area, where he worked for Macworld, Walmart.com, and Nike." # site description
    keywords = "web, project manager, producer, digital, developer" # site keywords
    license= '<a rel="license" href="http://creativecommons.org/licenses/by-nc/4.0/" target="_blank">CC by-SA 4.0</a>'

[params.social]
    GitHub = "cpoff"
    Twitter = "cpoff"
    Email   = "curt.poff@gmail.com"
    Instagram = "cpoff"
    LinkedIn = "cpoff"
#    Facebook = "Fatback"
    Telegram = "cpoff"
#    Dribbble = "xxoo"
    Keybase = "cpoff"

[blackfriday]
    angledQuotes = false
    extensions = ["hardLineBreak"]
    fractions = false
    plainIDAnchors = true
